"use client";
import { useState } from "react";
import { apiFetch } from "@/lib/api-fetch";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
type Sequence={id:string;name:string;episodeId:string|null;status:string;avStatus:string;revisionNumber:number;finalVideoUrl:string|null};
export function BlackfistShowrunner({projectId,episodeId}:{projectId:string;episodeId:string}){
 const [idea,setIdea]=useState("");const [busy,setBusy]=useState(false);const [sequences,setSequences]=useState<Sequence[]>([]);
 async function load(){setBusy(true);try{const r=await apiFetch(`/api/projects/${projectId}/sequences`);if(!r.ok)throw Error("Unable to load production");const data=await r.json() as Sequence[];setSequences(data.filter(x=>x.episodeId===episodeId))}catch(e){toast.error(e instanceof Error?e.message:"Unable to load production")}finally{setBusy(false)}}
 return <section className="rounded-xl border p-5 space-y-4"><header><h2 className="text-xl font-bold">BlackFist Showrunner</h2><p className="text-sm text-muted-foreground">Your characters. Your canon. Your original television episodes.</p></header><div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border p-3"><b>1 · Story</b><p className="text-xs text-muted-foreground">Develop your original episode and story arc.</p></div><div className="rounded-lg border p-3"><b>2 · Cast &amp; Continuity</b><p className="text-xs text-muted-foreground">Use approved BlackFist characters and their locked appearances.</p></div><div className="rounded-lg border p-3"><b>3 · Production</b><p className="text-xs text-muted-foreground">Generate, review and approve sequences before assembly.</p></div></div><label className="block text-sm font-medium" htmlFor="blackfist-episode-idea">Episode concept</label><textarea id="blackfist-episode-idea" className="w-full rounded-md border bg-background p-3 text-sm" value={idea} onChange={e=>setIdea(e.target.value)} placeholder="General Jamaica confronts Blood Baron in Kingston..." rows={3}/><p className="text-xs text-muted-foreground">Concept drafting is local to this screen until a script-generation workflow is connected. It is not saved or submitted.</p><Button variant="outline" disabled={busy} onClick={load}>Load Episode Production</Button><div className="space-y-2">{sequences.map(s=><div key={s.id} className="flex items-center justify-between rounded-md border p-3 text-sm"><span>{s.name} · Revision {s.revisionNumber}</span><span>{s.avStatus==="approved"?"Approved":s.status}</span></div>)}{!sequences.length&&<p className="text-xs text-muted-foreground">Load production to see existing episode sequences.</p>}</div></section>;
}
