"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { apiFetch } from "@/lib/api-fetch";
import { toast } from "sonner";
import { Clapperboard } from "lucide-react";

export function SequencePlanner({projectId,scenes,onUpdated}:{projectId:string;scenes:Array<{id:string;title:string}>;onUpdated?:()=>void}) {
 const [sceneId,setSceneId]=useState(scenes[0]?.id||""); const [busy,setBusy]=useState(false); const [proposal,setProposal]=useState<{shotIds:string[];rationale:string;direction?:unknown[]}|null>(null); const [lastSequenceId,setLastSequenceId]=useState<string|null>(null); const [audioSummary,setAudioSummary]=useState<string>(""); const [cueSummary,setCueSummary]=useState<string>("");
 async function direct(){if(!sceneId)return;setBusy(true);try{const r=await apiFetch(`/api/projects/${projectId}/sequences/direct`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sceneId,shotIds:proposal?.shotIds,direction:proposal?.direction})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Lioncore could not direct sequence");setProposal(d);toast.success("Lioncore prepared a Multi-Shot sequence");}catch(e){toast.error(e instanceof Error?e.message:"Could not direct sequence");}finally{setBusy(false)}}
 async function create(){if(!sceneId)return;setBusy(true);try{const r=await apiFetch(`/api/projects/${projectId}/sequences`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sceneId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create sequence");setLastSequenceId(d.id); setAudioSummary(""); setCueSummary(""); toast.success("BlackFist Multi-Shot sequence created");onUpdated?.();}catch(e){toast.error(e instanceof Error?e.message:"Could not create sequence");}finally{setBusy(false)}}
 async function planAudio(){if(!lastSequenceId)return;setBusy(true);try{const r=await apiFetch(`/api/projects/${projectId}/sequences/${lastSequenceId}/audio`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not plan sequence audio");const p=d.audioPlan||{};setAudioSummary(`Ambience: ${p.ambience?.length||0} · Dialogue: ${p.dialogue?.length||0} · SFX: ${p.sfx?.length||0} · Music: ${p.music?.length||0}`);toast.success("Lioncore Audio + SFX sequence planned");}catch(e){toast.error(e instanceof Error?e.message:"Could not plan audio");}finally{setBusy(false)}}
 async function compileCues(){if(!lastSequenceId)return;setBusy(true);try{const r=await apiFetch(`/api/projects/${projectId}/sequences/${lastSequenceId}/audio/cues`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not compile audio cues");const c=d.counts||{};setCueSummary(`Dialogue ${c.dialogue||0} · SFX ${c.sfx||0} · Ambience ${c.ambience||0} · Music ${c.music||0} · Bridges ${c.transition||0}`);toast.success("Audio production cue sheet ready");}catch(e){toast.error(e instanceof Error?e.message:"Could not compile cues");}finally{setBusy(false)}}
 return <section className="rounded-xl border p-4 space-y-3"><div className="flex items-center gap-2"><Clapperboard className="h-4 w-4"/><h3 className="font-semibold">BlackFist Sequence Planner</h3></div><p className="text-xs text-muted-foreground">Create a provider-independent 2–5 shot production block. Runway, OpenArt and future engines can execute the same locked plan.</p><div className="flex gap-2"><select className="min-w-0 flex-1 rounded-md border bg-background px-3 py-2 text-sm" value={sceneId} onChange={e=>setSceneId(e.target.value)}>{scenes.map(s=><option key={s.id} value={s.id}>{s.title||"Untitled scene"}</option>)}</select><Button variant="outline" disabled={busy||!sceneId} onClick={direct}>Lioncore Direct</Button><Button disabled={busy||!sceneId} onClick={create}>{proposal ? `Create ${proposal.shotIds.length}-Shot Plan` : "Create Multi-Shot Plan"}</Button></div>{lastSequenceId && <div className="flex items-center gap-2"><Button variant="outline" disabled={busy} onClick={planAudio}>Plan Audio + SFX</Button>{audioSummary && <span className="text-xs text-muted-foreground">{audioSummary}</span>}{audioSummary && <Button variant="outline" disabled={busy} onClick={compileCues}>Build Cue Sheet</Button>}</div>{cueSummary && <div className="rounded-md border p-2 text-xs"><b>Audio cue sheet:</b> {cueSummary}</div>}}{proposal && <div className="rounded-md border p-2 text-xs"><b>Lioncore proposal:</b> {proposal.shotIds.length} shots. {proposal.rationale}</div>}</section>;
}
